/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PageBookList: typeof import('./src/views/upload/components/pageBookList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Upload: typeof import('./src/components/Upload.vue')['default']
    UploadBook: typeof import('./src/views/upload/components/uploadBook.vue')['default']
    UploadList: typeof import('./src/views/upload/components/uploadList.vue')['default']
  }
}
